// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa5q_YgSWA7kNdlGr1GmUzoaF4BK01Las',
    appId: '1:1070666957559:web:00e0eb17aa725a022089f2',
    messagingSenderId: '1070666957559',
    projectId: 'arabian-majlis-3fa73',
    authDomain: 'arabian-majlis-3fa73.firebaseapp.com',
    storageBucket: 'arabian-majlis-3fa73.firebasestorage.app',
    measurementId: 'G-D6RLPHPB4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fmAdSSOeGUu-_DUwXBgT3RB4nwRLyw8',
    appId: '1:1070666957559:android:905f6a2b64a5162a2089f2',
    messagingSenderId: '1070666957559',
    projectId: 'arabian-majlis-3fa73',
    storageBucket: 'arabian-majlis-3fa73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8ja_OFYNWzSYvBtNllBu_zddCwrzRPY',
    appId: '1:1070666957559:ios:37315df1473cc3612089f2',
    messagingSenderId: '1070666957559',
    projectId: 'arabian-majlis-3fa73',
    storageBucket: 'arabian-majlis-3fa73.firebasestorage.app',
    iosBundleId: 'com.example.arabianMajlis',
  );
}
